
// Get all list
GET http://localhost:5000/api/v1/list



###
// Create a user
POST http://localhost:5000/api/v1/list
Content-Type: application/json

{
  "user": {
    "name": "new user"
  }
}


###
// Delete a user
DELETE http://localhost:5000/api/v1/list



###
// Update a user
PUT http://localhost:5000/api/v1/list
Content-Type: application/json

{
  "user": {
    "name": "new user"
  }
}